[workspace]
members = [
    "android_log",
    "bshook",
    "derive",
    "examples/config",
    "examples/offsetless_hook",
    "il2cpp",
    "inline_hook",
]
exclude = [
    "examples",
    "resources",
]
