[package]
name = "bshook_inline_hook"
version = "0.1.0"
authors = ["Raphaël Thériault <raphael_theriault@outlook.com>"]
edition = "2018"
license = "MIT"
build = "build.rs"

[build-dependencies]
cc = "1.0"
